export const axisLabelDict = [
  { value: "covidsym2_1", label: "Coughing" },
  { value: "covidsym2_2", label: "Sneezing" },
  { value: "covidsym2_3", label: "Runny/blocked nose" },
  { value: "covidsym2_4", label: "Mild fatigue" },
  { value: "covidsym2_5", label: "Severe fatigue" },
  { value: "covidsym2_6", label: "Numbness/tingling" },
  { value: "covidsym2_7", label: "Muscle cramp/ache" },
  { value: "covidsym2_8", label: "Pain in joints" },
  { value: "covidsym2_9", label: "Difficulty sleeping" },
  { value: "covidsym2_10", label: "Appetite loss" },
  { value: "covidsym2_11", label: "None of the above" },
  { value: "covidsym2_12", label: "Prefer not to say" },
  { value: "covidsym2_13", label: "Leg swelling" },
  { value: "covidsym2_14", label: "Weight loss" },

  { value: "covidsym3_1", label: "Itchy/sore eyes" },
  { value: "covidsym3_2", label: "Vision issues" },
  { value: "covidsym3_3", label: "Hearing issues" },
  { value: "covidsym3_4", label: "Hair loss" },
  { value: "covidsym3_5", label: "Hoarse voice" },
  { value: "covidsym3_6", label: "Skin issues" },
  { value: "covidsym3_7", label: "Face/lip swelling" },
  { value: "covidsym3_8", label: "Blisters on feet" },
  { value: "covidsym3_9", label: "Something else" },
  { value: "covidsym3_10", label: "None of the above" },
  { value: "covidsym3_11", label: "Prefer not to say" },
];
