export const axisLabelDict = [
  { value: "symptnowaw_1", label: "Loss sense of smell" },
  { value: "symptnowaw_2", label: "Loss sense of taste" },
  { value: "symptnowaw_3", label: "Persistent cough" },
  { value: "symptnowaw_4", label: "Fever" },
  { value: "symptnowaw_5", label: "Runny nose" },
  { value: "symptnowaw_6", label: "Sneezing" },
  { value: "symptnowaw_7", label: "Blocked nose" },
  { value: "symptnowaw_8", label: "Sore eyes" },
  { value: "symptnowaw_9", label: "Sore throat" },
  { value: "symptnowaw_10", label: "Hoarse voice" },
  { value: "symptnowaw_11", label: "Headache" },
  { value: "symptnowaw_12", label: "Dizziness" },
  { value: "symptnowaw_13", label: "Appetite loss" },
  { value: "symptnowaw_14", label: "Nausea/Vomiting" },
  { value: "symptnowaw_15", label: "Diarrhoea" },
  { value: "symptnowaw_16", label: "Abdominal pain" },
  { value: "symptnowaw_17", label: "Shortness of breath" },
  { value: "symptnowaw_18", label: "Tightness in chest" },
  { value: "symptnowaw_19", label: "Chest pain" },
  { value: "symptnowaw_20", label: "Chills" },
  { value: "symptnowaw_21", label: "Difficulty sleeping" },
  { value: "symptnowaw_22", label: "Fatigue" },
  { value: "symptnowaw_23", label: "Severe fatigue" },
  { value: "symptnowaw_24", label: "Numbness/tingling" },
  { value: "symptnowaw_25", label: "Heaviness arms/legs" },
  { value: "symptnowaw_26", label: "Achy muscles" },
  { value: "symptnowaw_27", label: "Don't know" },
  { value: "symptnowaw_28", label: "No symptom" },
  { value: "symptnowaw_29", label: "Leg swelling" },
];
